#!/bin/bash
#=======================================================================================
# Description: Simple start/stop script for Hadoop services.
#=======================================================================================

action=$1
service=$2

if [ -z "$action" ] || [ -z "$service" ]; then
    echo "Invalid arguments, must provide an action and service (example): start nodemanager"
    exit 1
fi
if [ "$action" != "start" ] && [ "$action" != "stop" ]; then
    echo "Only support start/stop actions."
    exit 1
fi

case $service in
    "namenode"|"datanode") hadoop-daemon.sh $action $service;;
    "resourcemanager"|"nodemanager") yarn-daemon.sh $action $service;;
    "historyserver")  mr-jobhistory-daemon.sh $action $service;;
    *) echo "Invalid Service: $service"
esac
